### ISSUE TITLE
Add extra glyphs from glyphtionary?

### ISSUE THREAD

**Issue by ento** [ento/ingress-shaper-glyphs#1]
- consequence
- creativity (triangular one)
- destination
- enlightened type b
- interrupt
- legacy
- live again / reincarnate
- mystery
- perspective
- presence
- resistance type b
- worth

**Comment by aviskase** [comment]
Any work on this? With the new Translator badge it will be important update :wink: 
Also missing:
- after
- before
- N'zeer
- unbounded

**Comment by ento** [comment]
I'll happily take pull requests, but Ingress is getting less and less priority on my to-do list :(
Closing this for now.
