### ISSUE TITLE
"No" glyph should be "inside"

### ISSUE THREAD

**Issue by nixiso** [ento/ingress-shaper-glyphs#3]
As per topic

**Comment by ento** [comment]
Inside is listed as an alternative name for No: https://github.com/ento/ingress-shaper-glyphs/blob/d92d4418969d52414ae8e3945eb59aa0e6e4fed2/src/glyphs.csv#L73

Also: I'm no longer actively playing Ingress and won't be maintaining this repo in the foreseeable future. If that wasn't the case, I would've liked to know how else the data could be improved.. but as things stand, I'm going to close this issue and archive the repo to express the state of this repo clearly.
